name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Se connecter à Azure avec Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Déployer l'API sur Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "fastapi-sentiment"
          package: .

      - name: Lancer les tests
        run: pytest

      - name: Se déconnecter d’Azure
        run: az logout
