name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Définir le PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Lancer les tests unitaires
        run: pytest tests/

      - name: Se connecter à Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Déployer l'API
        uses: azure/webapps-deploy@v2
        with:
          app-name: "fastapi-sentiment"
          package: .
